- name: Deploy Default Template Setup
  hosts: all
  become: yes
  vars_files:
    - ../private/vault.yml
  vars:
    ansible_user: "{{ ansible_user }}"
  tasks:
    - name: Configure UTC Timezone
      file:
        src: /usr/share/zoneinfo/UTC
        dest: /etc/localtime
        owner: root
        group: root
        state: link
      register: timezone
    - name: Update YUM configuration
      lineinfile:
        path: /etc/yum.conf
        regexp: '^installonly_limit='
        line: 'installonly_limit=2'
        backup: yes
    - name: Update the OS
      package:
        name: '*'
        state: latest
      register: updated
    - name: Reboot the OS
      reboot:
      when: updated.changed or timezone.changed
    - name: Update SSHd Configuration
      copy:
        src: ./templates/sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0600'
        backup: yes
      register: sshdconfigupdated
    - name: Restart sshd
      service:
        name: sshd
        state: restarted
      when: sshdconfigupdated.changed
    - name: Update swappinness value
      sysctl:
        name: vm.swappiness
        value: '10'
        state: present
    - name: Install epel-release
      package:
        name: epel-release
        state: present
    - name: Install base set of packages
      package:
        name:
          - wget
          - zip
          - screen
          - tcpdump
          - yum-cron
          - deltarpm
          - ntp
          - ntpdate
          - system-storage-manager
          - policycoreutils-python
          - epel-release
          - virt-what
          - unzip
          - firewalld
          - htop
        state: present
    - name: Enable and start firewalld
      service:
        name: firewalld
        enabled: yes
        state: started
    - name: Check for virtualization
      shell: virt-what
      register: virtualization
    - name: Install QEMU Guest Agent
      yum:
        pkg:
          - qemu-guest-agent
        state: present
      when: virtualization.stdout=='kvm'
    - name: Enable QEMU Guest Agent
      service:
        name: qemu-guest-agent
        enabled: yes
        state: started
      when: virtualization.stdout=='kvm'
    - name: Disable all existing NTP servers
      replace:
        path: /etc/ntp.conf
        regexp: '(?:^server (?!pool.ntp.org).*)'
        backup: yes
    - name: Configure NTP server
      lineinfile:
        path: /etc/ntp.conf
        regexp: '^server pool.ntp.org'
        line: 'server pool.ntp.org'
        backup: yes
      register: ntpconfigupdated
    - name: Enable ntpd
      service:
        name: ntpd
        enabled: yes
    - name: Stop ntpd
      service:
        name: ntpd
        state: stopped
    - name: Check time delta
      shell: "ntpdate -q pool.ntp.org | grep -Eo 'offset .* sec' | awk '{ print $2 }'"
      register: timedelta
    - name: Force time synchronization
      command:
        cmd: 'ntpdate -s pool.ntp.org'
      when: timedelta.stdout|float > 2.0
    - name: Start ntpd
      service:
        name: ntpd
        state: restarted
      when: ntpconfigupdated.changed
    - name: Setup administrative users
      block:
        - name: Add management users
          user:
            name: "{{ item.key }}"
            uid: "{{ item.value.uid }}"
            comment: "{{ item.value.comment }}"
            groups: wheel
          with_dict: "{{ management_users }}"
        - name: Add management SSH keys
          authorized_key:
            user: "{{ item.key }}"
            state: present
            key: "{{ lookup('file', '../private/{{ item.key }}_key.pub') }}"
          with_dict: "{{ management_users }}"
        - name: Add management sudoers
          lineinfile:
            path: "/etc/sudoers.d/{{ item.key }}"
            create: yes
            regexp: "^{{ item.key }}"
            line: "{{ item.key }}        ALL=(ALL)       NOPASSWD: ALL"
          with_dict: "{{ management_users }}"
